name: Dummy workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      TRACKING_NUMBERS: ${{ vars.TRACKING_NUMBERS }}
      NTFY_TOPIC: ${{ vars.NTFY_TOPIC }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
      - name: Test access to Onex
        run: |
          python3 onex_track.py -T "$NTFY_TOPIC" --track $TRACKING_NUMBERS -vnc
