name: Track my parcels

on:
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-24.04
    env:
      TRACKING_NUMBERS: ${{ vars.TRACKING_NUMBERS }}
      NTFY_TOPIC: ${{ vars.NTFY_TOPIC }}
      PANTRY_BASKET_ID: ${{ PANTRY_BASKET_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
      - name: Run tracking script
        run: |
          python3 onex_track.py --ntfy-topic "$NTFY_TOPIC" \
                                --pantry-basket "$PANTRY_BASKET_ID" \
                                --track "$TRACKING_NUMBERS" \
                                --split-by-newlines \
                                --no-notification \
                                --verbose
