name: Track my parcels

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '23 */3 * * *'
jobs:
  track:
    runs-on: ubuntu-24.04
    env:
      TRACKING_NUMBERS: ${{ vars.TRACKING_NUMBERS }}
      NTFY_TOPIC: ${{ vars.NTFY_TOPIC }}
      JSON_BIN_ID: ${{ vars.JSON_BIN_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp babel
      - name: Run tracking script
        run: |
          python3 onex_track.py --ntfy-topic "$NTFY_TOPIC" \
                                --json-bin "$JSON_BIN_ID" \
                                --track "$TRACKING_NUMBERS" \
                                --split-by-newlines \
                                --verbose
